version: 0.2
phases:
  build:
    commands:
        #- cd $CODEBUILD_SRC_DIR_frontend_Code
        #- cd $CODEBUILD_SRC_DIR_backend_code
        - echo "here we start"
        - docker-compose --file docker-compose-orginal.1.yml build 
        - docker tag con-frontend:latest 257795908217.dkr.ecr.eu-central-1.amazonaws.com/conduit/frontend
        - docker push 257795908217.dkr.ecr.eu-central-1.amazonaws.com/conduit/frontend
        - docker tag con-backend:latest 257795908217.dkr.ecr.eu-central-1.amazonaws.com/conduit/backend
        - docker push 257795908217.dkr.ecr.eu-central-1.amazonaws.com/conduit/backend

        
