version: 0.2
phases:
  build:
    commands:
        #- ls 
        #- pwd
        #- cd $CODEBUILD_SRC_DIR_frontend_Code
        #- ls 
        #- pwd
        #- cd $CODEBUILD_SRC_DIR_backend_code
        #- ls 
        #- pwd
        - echo "here we start"
        - docker-compose --file docker-compose-orginal.1.yml build 