version: '3'
services:

  #PHP Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: con-backend
    container_name: con-backend
    restart: unless-stopped
    tty: true
    ports:
      - "49160:8080"
    working_dir: /usr/src/app
    networks:
      - app-network

  #Nginx Service
  frontend:
    build:
      context: ./../01
      dockerfile: Dockerfile
      args:
        REACT_APP_BACKEND_URL: "http://conduit-alb-1492634757.eu-central-1.elb.amazonaws.com:49160/api"
    image: con-frontend
    container_name: con-frontend
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    working_dir: /app
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge